export const ANIMATION = {
  fall: {
    anticipationScale: 1.12,
    anticipationDuration: 0.1,
    fallDuration: 0.17,
    verticalMove: -0.12,
    vanishDuration: 0.02,
  },
  sticker: {
    startScale: 0.9,
    impactScale: 0.96,
    reboundScale: 1.035,
    finalScale: 1.0,
    startRotation: -4.1,
    impactRotation: -4.65,
    reboundRotation: -5.35,
    finalRotation: -5,
    revealDuration: 0.025,
    squashDuration: 0.055,
    reboundDuration: 0.11,
    settleDuration: 0.14,
  },
  shadow: {
    startX: 8,
    startY: 16,
    impactX: 14,
    impactY: 25,
    finalX: 5,
    finalY: 13,
    startOpacity: 0,
    impactOpacity: 0.82,
    finalOpacity: 0.62,
  },
  dust: {
    count: 18,
    minDistance: 18,
    maxDistance: 48,
    minSize: 2,
    maxSize: 5,
    minDuration: 0.16,
    maxDuration: 0.32,
  },
  impact: {
    startBlur: 3,
    revealBlur: 1.5,
    settleBlur: 0,
    startBrightness: 1.16,
  },
  position: {
    yOffset: -25,
  },
} as const;
